/**
 * Seeds the LOCAL chain with real elections so the dApp has genuine on-chain
 * data to render during development. Deliberately local-only: it uses Hardhat's
 * dev accounts and a throwaway Paillier key.
 *
 * Usage: npx hardhat run scripts/seed-local.ts --network localhost
 */
import { network } from "hardhat";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const { ethers } = await network.connect();

const HOUR = 3600;

// Throwaway Paillier public key (real keys are generated by the UI at creation).
const DEMO_PAILLIER_PK = JSON.stringify({ n: "0x" + "ab".repeat(64), g: "0x" + "ab".repeat(64) });

async function main() {
  const chainId = (await ethers.provider.getNetwork()).chainId;
  if (chainId !== 31337n) {
    throw new Error(`seed-local is for the local chain only (got chainId ${chainId})`);
  }

  const root = join(dirname(fileURLToPath(import.meta.url)), "..");
  const manifest = JSON.parse(readFileSync(join(root, "deployments", "local.json"), "utf-8")) as {
    contracts: { ElectionFactory: string; PoseidonT3: string };
  };

  const [deployer] = await ethers.getSigners();
  const factory = await ethers.getContractAt(
    "ElectionFactory",
    manifest.contracts.ElectionFactory,
    deployer,
  );

  const now = Math.floor(Date.now() / 1000);

  const elections = [
    {
      name: "Madrid City Council — District 5 Representative",
      votingType: 0, // SIMPLE_PLURALITY
      thresholdValue: 0n,
      candidates: [
        { name: "Ana García López", description: "Progressive Alliance — urban mobility" },
        { name: "Carlos Martínez Ruiz", description: "People's Party — former district manager" },
        { name: "Sofía Herrera Vega", description: "Green Coalition — environmental engineer" },
      ],
      // Enrollment open right now
      enrollStart: now - HOUR,
      enrollEnd: now + 24 * HOUR,
      voteStart: now + 24 * HOUR,
      voteEnd: now + 72 * HOUR,
      organizerName: "Madrid Municipal Authority",
    },
    {
      name: "UB Student Union — Bylaw Amendment",
      votingType: 2, // SUPERMAJORITY_TWO_THIRDS (Yes/No)
      thresholdValue: 0n,
      candidates: [{ name: "Yes" }, { name: "No" }],
      // Voting active right now
      enrollStart: now - 48 * HOUR,
      enrollEnd: now - HOUR,
      voteStart: now - HOUR,
      voteEnd: now + 48 * HOUR,
      organizerName: "Universidad de Barcelona",
    },
    {
      name: "Cooperative Board — Witness Confirmation",
      votingType: 3, // WITNESS_THRESHOLD (Yes/No, N witnesses)
      thresholdValue: 4n,
      candidates: [{ name: "Yes" }, { name: "No" }],
      enrollStart: now - HOUR,
      enrollEnd: now + 12 * HOUR,
      voteStart: now + 12 * HOUR,
      voteEnd: now + 96 * HOUR,
      organizerName: "Seville Tech Hub Collective",
    },
  ];

  for (const e of elections) {
    const cfg = {
      name: e.name,
      votingType: e.votingType,
      thresholdValue: e.thresholdValue,
      numOptions: BigInt(e.candidates.length),
      enrollStart: e.enrollStart,
      enrollEnd: e.enrollEnd,
      voteStart: e.voteStart,
      voteEnd: e.voteEnd,
      scope: BigInt(ethers.hexlify(ethers.randomBytes(31))),
      paillierPublicKey: DEMO_PAILLIER_PK,
      metadataJson: JSON.stringify({
        description: `${e.name} — seeded locally for development.`,
        organizerName: e.organizerName,
        candidates: e.candidates,
        privacyQuorum: 3,
        tags: ["local", "dev"],
      }),
    };

    const tx = await factory.createElection(cfg, { value: ethers.parseEther("1") });
    const receipt = await tx.wait();
    const created = receipt!.logs
      .map(l => { try { return factory.interface.parseLog(l); } catch { return null; } })
      .find(p => p?.name === "ElectionCreated");
    console.log(`✓ ${e.name}\n   → ${created?.args?.electionAddress}`);
  }

  console.log(`\nTotal elections on chain: ${await factory.electionsCount()}`);
  console.log(`Organizer (Hardhat account #0): ${deployer.address}`);
}

await main();
