/**
 * The arithmetic of a Votain ballot, and the proof that a tally is correct.
 *
 * WHY THIS SCHEME. Ballots are exponential ElGamal over Baby Jubjub, the
 * curve the ballot circuit (circuits/src/ballot.circom) can compute on, which
 * is what lets a voter prove a ballot well formed AND cancel their previous one
 * without revealing which. See the circuit for the construction. A ballot is:
 *
 *   vote    A  = r·G,              B_i  = v_i·G + r·H_i
 *   cancel  A' = -A_prev + s·G,    B'_i = -B_prev_i + s·H_i
 *
 * with one tally key H_i = x_i·G per slot (options plus the blank vote).
 * Adding every vote and every cancellation on chain telescopes each voter's
 * chain to their LAST vote, so the aggregate decrypts straight to the counts:
 *
 *   M_i = ΣB_i - x_i·ΣA = count_i·G
 *
 * and count_i is recovered by a baby-step giant-step search, bounded by the
 * number of ballots.
 *
 * THE PROOF that a tally is right is the tally circuit's
 * (circuits/src/tally.circom), checked by the election on chain against the
 * aggregate it accumulated itself; nothing here needs to be trusted for it.
 *
 * Deliberately free of dependencies, like the module it replaces: the browser,
 * the auditor's CLI and the contract tests import this one file. Poseidon is
 * passed in where it is needed, since each of them already has one.
 */

// ────────────────────────────────────────────────
// The curve
// ────────────────────────────────────────────────

/** The BN254 scalar field: Baby Jubjub's base field and the circuit's field. */
export const FIELD = 21888242871839275222246405745257275088548364400416034343698204186575808495617n;
/** Order of the prime subgroup generated by `BASE`. */
export const SUBGROUP_ORDER = 2736030358979909402780800718157159386076813972158567259200215660948447373041n;

const A_COEFF = 168700n;
const D_COEFF = 168696n;

export type Point = readonly [bigint, bigint];

export const IDENTITY: Point = [0n, 1n];
/** Base8, the generator the circuit and Semaphore use. */
export const BASE: Point = [
  5299619240641551281634865583518297030282874472190772894086521144482721001553n,
  16950150798460657717958625567821834550301663161624707787222815936182638968203n,
];

const mod = (a: bigint, m: bigint = FIELD): bigint => ((a % m) + m) % m;


/** Modular inverse by extended Euclid, far cheaper than a Fermat power here. */
function inverse(a: bigint): bigint {
  let [oldR, r] = [mod(a), FIELD];
  let [oldS, s] = [1n, 0n];
  while (r !== 0n) {
    const q = oldR / r;
    [oldR, r] = [r, oldR - q * r];
    [oldS, s] = [s, oldS - q * s];
  }
  return mod(oldS);
}

/**
 * Extended twisted Edwards coordinates (X:Y:Z:T), x = X/Z, y = Y/Z, xy = T/Z.
 *
 * Additions need no inversion here, so a scalar multiplication pays for one,
 * at the end, instead of one per step: the difference between a tally that
 * takes seconds and one that takes minutes.
 */
type Extended = [bigint, bigint, bigint, bigint];

const toExtended = ([x, y]: Point): Extended => [x, y, 1n, mod(x * y)];

function toAffine([x, y, z]: Extended): Point {
  const zi = inverse(z);
  return [mod(x * zi), mod(y * zi)];
}

/** add-2008-hwcd: complete on Baby Jubjub, whose d is not a square. */
function addExtended(p: Extended, q: Extended): Extended {
  const [x1, y1, z1, t1] = p;
  const [x2, y2, z2, t2] = q;
  const a = mod(x1 * x2);
  const b = mod(y1 * y2);
  const c = mod(D_COEFF * t1 * t2);
  const d = mod(z1 * z2);
  const e = mod((x1 + y1) * (x2 + y2) - a - b);
  const f = mod(d - c);
  const g = mod(d + c);
  const h = mod(b - A_COEFF * a);
  return [mod(e * f), mod(g * h), mod(f * g), mod(e * h)];
}

/** Twisted Edwards addition, complete on Baby Jubjub. */
export function add(p: Point, q: Point): Point {
  return toAffine(addExtended(toExtended(p), toExtended(q)));
}

export const negate = (p: Point): Point => [mod(-p[0]), p[1]];

function multiplyExtended(p: Point, scalar: bigint): Point {
  let result: Extended = [0n, 1n, 1n, 0n];
  let addend = toExtended(p);
  let e = scalar;
  while (e > 0n) {
    if (e & 1n) result = addExtended(result, addend);
    addend = addExtended(addend, addend);
    e >>= 1n;
  }
  return toAffine(result);
}

export const multiply = (p: Point, scalar: bigint): Point =>
  multiplyExtended(p, mod(scalar, SUBGROUP_ORDER));

export const equals = (p: Point, q: Point): boolean => p[0] === q[0] && p[1] === q[1];

export function isOnCurve(p: Point): boolean {
  const [x, y] = p;
  if (x < 0n || x >= FIELD || y < 0n || y >= FIELD) return false;
  const xx = mod(x * x);
  const yy = mod(y * y);
  return mod(A_COEFF * xx + yy) === mod(1n + D_COEFF * xx * yy);
}

/** A point of the prime subgroup: on the curve, and killed by its order. */
export const isInSubgroup = (p: Point): boolean =>
  isOnCurve(p) && equals(multiplyExtended(p, SUBGROUP_ORDER), IDENTITY);

/** A uniformly random scalar in [1, l). */
export function randomScalar(): bigint {
  for (;;) {
    const bytes = crypto.getRandomValues(new Uint8Array(40));
    const value = bytesToBigInt(bytes) % SUBGROUP_ORDER;
    if (value !== 0n) return value;
  }
}

function bytesToBigInt(bytes: Uint8Array): bigint {
  let x = 0n;
  for (const b of bytes) x = (x << 8n) | BigInt(b);
  return x;
}

// ────────────────────────────────────────────────
// Ballots
// ────────────────────────────────────────────────

/** One ballot as the chain records it: a vote and a cancellation. */
export interface Ballot {
  tag: bigint;
  voteA: Point;
  voteB: Point[];
  cancelA: Point;
  cancelB: Point[];
}

/** The vote part of a fresh ballot, for `slots` slots, voting `choice`. */
export function encryptVote(keys: readonly Point[], choice: number, r: bigint): { a: Point; b: Point[] } {
  if (!Number.isInteger(choice) || choice < 0 || choice >= keys.length) {
    throw new Error(`not an option index: ${choice}`);
  }
  return {
    a: multiply(BASE, r),
    b: keys.map((h, i) => add(i === choice ? BASE : IDENTITY, multiply(h, r))),
  };
}

/** The cancellation of `previous` (or of nothing), re-randomised with `s`. */
export function encryptCancellation(
  keys: readonly Point[],
  s: bigint,
  previous: { a: Point; b: readonly Point[] } | null,
): { a: Point; b: Point[] } {
  const prevA = previous?.a ?? IDENTITY;
  return {
    a: add(negate(prevA), multiply(BASE, s)),
    b: keys.map((h, i) => add(negate(previous?.b[i] ?? IDENTITY), multiply(h, s))),
  };
}

/** Everything cast, added up: one A and one B per slot. */
export function aggregate(ballots: readonly Ballot[], slots: number): { a: Point; b: Point[] } {
  let a: Point = IDENTITY;
  const b: Point[] = Array.from({ length: slots }, () => IDENTITY);
  for (const ballot of ballots) {
    a = add(add(a, ballot.voteA), ballot.cancelA);
    for (let i = 0; i < slots; i++) b[i] = add(add(b[i], ballot.voteB[i]), ballot.cancelB[i]);
  }
  return { a, b };
}

/**
 * The m with m·G = target, for 0 <= m <= bound, by baby-step giant-step.
 * Null when there is none, which on an honest chain cannot happen.
 */
export function discreteLog(target: Point, bound: number): bigint | null {
  const step = Math.max(1, Math.ceil(Math.sqrt(bound + 1)));
  const table = new Map<string, number>();
  let p: Point = IDENTITY;
  for (let j = 0; j < step; j++) {
    table.set(`${p[0]}:${p[1]}`, j);
    p = add(p, BASE);
  }
  const giant = negate(multiply(BASE, BigInt(step)));
  let gamma = target;
  for (let i = 0; i <= step; i++) {
    const j = table.get(`${gamma[0]}:${gamma[1]}`);
    if (j !== undefined) {
      const m = BigInt(i * step + j);
      return m <= BigInt(bound) ? m : null;
    }
    gamma = add(gamma, giant);
  }
  return null;
}

// ────────────────────────────────────────────────
// Hashes the circuit also computes (Poseidon passed in)
// ────────────────────────────────────────────────

export type Poseidon = (inputs: bigint[]) => bigint;

/** Domain separators, as in the circuit. */
export const TAG_DOMAIN = 1953718116n;
export const EPOCH_DOMAIN = 1701867371n;

/** Poseidon chain over points, seeded with `seed`: HashPoints in the circuit. */
export function hashPoints(poseidon3: Poseidon, seed: bigint, points: readonly Point[]): bigint {
  return points.reduce((h, p) => poseidon3([h, p[0], p[1]]), seed);
}

/** What the circuit takes as `keysHash`: the keys, padded with the identity. */
export function keysHash(poseidon3: Poseidon, keys: readonly Point[], circuitSlots: number): bigint {
  return hashPoints(poseidon3, 0n, padPoints(keys, circuitSlots));
}

/** A ballot's leaf in the ballots tree: BallotLeaf in the circuit. */
export function ballotLeaf(poseidon3: Poseidon, tag: bigint, a: Point, b: readonly Point[]): bigint {
  return hashPoints(poseidon3, poseidon3([tag, a[0], a[1]]), b);
}

/** The voter's tag at step k of their chain in one election. */
export const ballotTag = (poseidon4: Poseidon, secret: bigint, scope: bigint, k: bigint): bigint =>
  poseidon4([TAG_DOMAIN, secret, scope, k]);

/** The voter's tag for one epoch: at most one ballot per voter per epoch. */
export const epochTag = (poseidon4: Poseidon, secret: bigint, scope: bigint, epoch: bigint): bigint =>
  poseidon4([EPOCH_DOMAIN, secret, scope, epoch]);

export const padPoints = (points: readonly Point[], length: number): Point[] =>
  Array.from({ length }, (_, i) => points[i] ?? IDENTITY);

// ────────────────────────────────────────────────
// Tally keys
// ────────────────────────────────────────────────

/**
 * One key per slot, derived from a 32-byte secret and a per-election nonce.
 *
 * 48 bytes of HMAC output per key, reduced modulo l, so the reduction bias is
 * below 2^-128. The public keys are what the election stores.
 */
export async function deriveTallyKeys(
  secret: Uint8Array,
  keyNonce: string,
  slots: number,
): Promise<{ secrets: bigint[]; keys: Point[] }> {
  const key = await crypto.subtle.importKey(
    "raw",
    // A copy: a plain ArrayBuffer-backed view is what every WebCrypto accepts,
    // the browser's and Node's, whose type declarations differ.
    new Uint8Array(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const secrets: bigint[] = [];
  for (let i = 0; i < slots; i++) {
    const label = (part: number) => new TextEncoder().encode(`votain:tally-key:v2:${keyNonce}:${i}:${part}`);
    const one = new Uint8Array(await crypto.subtle.sign("HMAC", key, label(0)));
    const two = new Uint8Array(await crypto.subtle.sign("HMAC", key, label(1)));
    const x = bytesToBigInt(new Uint8Array([...one, ...two.slice(0, 16)])) % SUBGROUP_ORDER;
    secrets.push(x === 0n ? 1n : x);
  }
  return { secrets, keys: secrets.map(x => multiply(BASE, x)) };
}

// ────────────────────────────────────────────────
// The tally
// ────────────────────────────────────────────────

/**
 * The counts an aggregate decrypts to. Needs the keys.
 *
 * `bound` is the most any count can be, the number of ballots cast, which is
 * what keeps the discrete-log search short. Whether these counts reach the
 * chain is decided by the tally circuit, which proves them against the
 * aggregate the election itself accumulated.
 */
export function decryptTally(
  secrets: readonly bigint[],
  total: { a: Point; b: readonly Point[] },
  bound: number,
): bigint[] {
  return secrets.map((x, i) => {
    const m = add(total.b[i], negate(multiply(total.a, x)));
    const count = discreteLog(m, bound);
    if (count === null) throw new Error(`option ${i + 1} does not decrypt to a count of at most ${bound}`);
    return count;
  });
}

/** A key list as the contract stores it: x0, y0, x1, y1, ... */
export const flattenPoints = (points: readonly Point[]): bigint[] => points.flatMap(p => [p[0], p[1]]);

export function unflattenPoints(values: readonly bigint[]): Point[] {
  const out: Point[] = [];
  for (let i = 0; i + 1 < values.length; i += 2) out.push([values[i], values[i + 1]]);
  return out;
}

// ────────────────────────────────────────────────
// Circuit inputs
// ────────────────────────────────────────────────

/** A LeanIMT membership proof, as @zk-kit/lean-imt produces it. */
export interface MerklePath {
  root: bigint;
  index: number | bigint;
  siblings: readonly bigint[];
}

/** Depth the ballot circuit was compiled for, for both of its trees. */
export const CIRCUIT_MAX_DEPTH = 20;

const toStrings = (values: readonly bigint[]): string[] => values.map(v => v.toString());
const pointStrings = (p: Point): string[] => [p[0].toString(), p[1].toString()];

function pathInputs(path: MerklePath | null, maxDepth: number) {
  if (!path) return { depth: "0", index: "0", siblings: Array.from({ length: maxDepth }, () => "0") };
  if (path.siblings.length > maxDepth) throw new Error("tree deeper than the circuit supports");
  return {
    depth: String(path.siblings.length),
    index: BigInt(path.index).toString(),
    siblings: toStrings([...path.siblings, ...Array.from({ length: maxDepth - path.siblings.length }, () => 0n)]),
  };
}

/** What a cast ballot carries on chain, padded to the circuit's slots. */
export interface CastBallot {
  tag: bigint;
  epochTag: bigint;
  leaf: bigint;
  voteA: Point;
  voteB: Point[];
  cancelA: Point;
  cancelB: Point[];
}

/**
 * Everything the ballot circuit needs to prove one ballot, and the ballot.
 *
 * `keys` are the election's own slots; the circuit's extra slots are padded
 * with the identity, which is what `keysHash` hashes too. `previous` is the
 * voter's own last ballot and its path in the ballots tree, or null for their
 * first.
 */
export function ballotCircuitInputs(p: {
  poseidon3: Poseidon;
  poseidon4: Poseidon;
  circuitSlots: number;
  maxDepth?: number;
  secret: bigint;
  scope: bigint;
  epoch: bigint;
  keys: readonly Point[];
  choice: number;
  k: bigint;
  voters: MerklePath;
  ballotsRoot: bigint;
  previous: { a: Point; b: readonly Point[]; path: MerklePath } | null;
  r?: bigint;
  s?: bigint;
}): { inputs: Record<string, string | string[] | string[][]>; ballot: CastBallot } {
  const maxDepth = p.maxDepth ?? CIRCUIT_MAX_DEPTH;
  const keys = padPoints(p.keys, p.circuitSlots);
  const r = p.r ?? randomScalar();
  const s = p.s ?? randomScalar();

  // The encryption runs over the padded keys: identity keys give identity
  // components, which is what the circuit computes for unused slots.
  const vote = encryptVote(keys, p.choice, r);
  const previous = p.previous ? { a: p.previous.a, b: padPoints(p.previous.b, p.circuitSlots) } : null;
  const cancel = encryptCancellation(keys, s, previous);

  const tag = ballotTag(p.poseidon4, p.secret, p.scope, p.k);
  const ballot: CastBallot = {
    tag,
    epochTag: epochTag(p.poseidon4, p.secret, p.scope, p.epoch),
    leaf: ballotLeaf(p.poseidon3, tag, vote.a, vote.b),
    voteA: vote.a,
    voteB: vote.b,
    cancelA: cancel.a,
    cancelB: cancel.b,
  };

  const voters = pathInputs(p.voters, maxDepth);
  const ballots = pathInputs(p.previous?.path ?? null, maxDepth);
  const prevA = previous?.a ?? IDENTITY;
  const prevB = previous?.b ?? padPoints([], p.circuitSlots);

  return {
    ballot,
    inputs: {
      votersRoot: p.voters.root.toString(),
      ballotsRoot: p.ballotsRoot.toString(),
      scope: p.scope.toString(),
      keysHash: keysHash(p.poseidon3, p.keys, p.circuitSlots).toString(),
      slots: String(p.keys.length),
      epoch: p.epoch.toString(),
      voteA: pointStrings(vote.a),
      voteB: vote.b.map(pointStrings),
      cancelA: pointStrings(cancel.a),
      cancelB: cancel.b.map(pointStrings),
      secret: p.secret.toString(),
      votersDepth: voters.depth,
      votersIndex: voters.index,
      votersSiblings: voters.siblings,
      keys: keys.map(pointStrings),
      choice: Array.from({ length: p.circuitSlots }, (_, i) => (i === p.choice ? "1" : "0")),
      r: r.toString(),
      s: s.toString(),
      k: p.k.toString(),
      prevA: pointStrings(prevA),
      prevB: prevB.map(pointStrings),
      ballotsDepth: ballots.depth,
      ballotsIndex: ballots.index,
      ballotsSiblings: ballots.siblings,
    },
  };
}

/**
 * The inputs of the tally circuit, for publishing (`publish`) or for voiding
 * below the quorum. `aggregate` is the election's on-chain sum, padded.
 */
export function tallyCircuitInputs(p: {
  poseidon3: Poseidon;
  circuitSlots: number;
  keys: readonly Point[];
  secrets: readonly bigint[];
  counts: readonly bigint[];
  aggregate: { a: Point; b: readonly Point[] };
  quorum: bigint;
  publish: boolean;
}): Record<string, string | string[] | string[][]> {
  const pad = <T,>(values: readonly T[], filler: T) =>
    Array.from({ length: p.circuitSlots }, (_, i) => values[i] ?? filler);
  return {
    keysHash: keysHash(p.poseidon3, p.keys, p.circuitSlots).toString(),
    slots: String(p.keys.length),
    aggA: pointStrings(p.aggregate.a),
    aggB: padPoints(p.aggregate.b, p.circuitSlots).map(pointStrings),
    quorum: p.quorum.toString(),
    publish: p.publish ? "1" : "0",
    // An unused slot needs a valid scalar all the same; its key is forced to
    // the identity whatever this is.
    secrets: toStrings(pad(p.secrets, 1n)),
    count: toStrings(pad(p.counts, 0n)),
  };
}

// ────────────────────────────────────────────────
// Proofs, as the verifiers take them
// ────────────────────────────────────────────────

/** A Groth16 proof as snarkjs returns it. */
export interface SnarkProof {
  pi_a: readonly (string | bigint)[];
  pi_b: readonly (readonly (string | bigint)[])[];
  pi_c: readonly (string | bigint)[];
}

/** A Groth16 proof in the verifiers' calldata order: b's coordinates are swapped. */
export interface SolidityProof {
  a: [bigint, bigint];
  b: [[bigint, bigint], [bigint, bigint]];
  c: [bigint, bigint];
}

export function solidityProof(proof: SnarkProof): SolidityProof {
  const n = (v: string | bigint) => BigInt(v);
  return {
    a: [n(proof.pi_a[0]), n(proof.pi_a[1])],
    b: [
      [n(proof.pi_b[0][1]), n(proof.pi_b[0][0])],
      [n(proof.pi_b[1][1]), n(proof.pi_b[1][0])],
    ],
    c: [n(proof.pi_c[0]), n(proof.pi_c[1])],
  };
}

/** A cast ballot as `castVote` and `relayVote` take it. */
export function ballotCalldata(
  ballot: CastBallot,
  roots: { votersRoot: bigint; ballotsRoot: bigint; epoch: bigint },
) {
  return {
    votersRoot: roots.votersRoot,
    ballotsRoot: roots.ballotsRoot,
    epoch: roots.epoch,
    tag: ballot.tag,
    epochTag: ballot.epochTag,
    leaf: ballot.leaf,
    voteA: [...ballot.voteA] as [bigint, bigint],
    voteB: flattenPoints(ballot.voteB),
    cancelA: [...ballot.cancelA] as [bigint, bigint],
    cancelB: flattenPoints(ballot.cancelB),
  };
}
